name: tachidesk_sorayomi
description: A manga reader client for Suwayomi Server.

publish_to: "none"
version: 0.6.2+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  built_collection: ^5.1.1
  cached_network_image: ^3.2.2
  cached_network_image_platform_interface: ^4.0.0
  cupertino_icons: ^1.0.5
  extension_type_unions: ^1.0.10
  file_picker: ^8.0.0+1
  flex_color_scheme: ^8.0.0
  flutter:
    sdk: flutter
  flutter_android_volume_keydown:
    git: https://github.com/DattatreyaReddy/flutter_android_volume_keydown
  flutter_cache_manager: ^3.3.0
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.1
  fluttertoast: ^8.1.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  go_router: ^14.0.2
  gql: ^1.0.1-alpha+1730759315362
  gql_http_link: ^1.0.1+1
  graphql: ^5.2.0-beta.10
  graphql_flutter: ^5.2.0-beta.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.1.1
  http: ^1.2.0
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  network_info_plus: ^6.0.0
  package_info_plus: ^8.0.0
  path: ^1.8.3
  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  pub_semver: ^2.1.2
  queue: ^3.1.0+2
  riverpod_annotation: ^2.0.0
  scrollable_positioned_list: ^0.3.5
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  url_launcher: ^6.1.6
  web_socket_channel: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.14
  # flutter_flavorizr: ^2.1.5
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  go_router_builder: ^2.0.0
  graphql_codegen: ^1.1.1
  json_serializable: ^6.5.4
  lints: ^5.0.0
  riverpod_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/icons/launcher/

flutter_gen:
  output: lib/src/constants/gen/

flutter_native_splash:
  color: "#54C5F8"
  image: assets/icons/dark_icon.png
  branding: assets/icons/launcher/from_suwayomi.png
  color_dark: "#01579B"
  image_dark: assets/icons/light_icon.png
  android_12:
    color: "#54C5F8"
    color_dark: "#01579B"
    icon_background_color: "#54C5F8"
    icon_background_color_dark: "#01579B"
    image: assets/icons/dark_icon.png
    image_dark: assets/icons/light_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/launcher/sorayomi_icon.png"
  image_path_ios: "assets/icons/launcher/ios_sorayomi_icon.png"
  web:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
    background_color: "#54C5F8"
    theme_color: "#54C5F8"
  windows:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/launcher/sorayomi_icon.png"
