name: Build-Windows
on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"
env:
  pkg_name: tachidesk-sorayomi
jobs:
  create-build:
    name: Create Windows build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor -v
      - uses: actions/checkout@v3
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build windows --release
      # Copy VC redistributables
      - name: Copy VC redistributables
        working-directory: build\windows\x64\runner\Release
        run: Copy-Item (vswhere -latest -find 'VC\Redist\MSVC\*\x64\*\*.dll') .
      # Compress build
      - name: Compress build for Windows
        working-directory: build\windows\x64\runner\Release
        run: compress-archive -Path * -DestinationPath "${env:GITHUB_WORKSPACE}\${{ env.pkg_name }}-${{ github.ref_name }}-windows-x64.zip"
      # Add to release
      - name: Add packaged build to release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ format('{0}', github.event.head_commit.timestamp) }}
          draft: false
          files: ${{ env.pkg_name }}*
          token: ${{ secrets.GITHUB_TOKEN }}
