# Copyright (c) 2022 Contributors to the Suwayomi project
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: gh-Pages

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Only works with v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Recreating the project
      - run: flutter doctor -v
      - uses: actions/checkout@v3
      # - run: flutter create .
      - run: flutter pub get
      - run: flutter gen-l10n
      - run: dart run build_runner build --delete-conflicting-outputs

      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          baseHref: /Tachidesk-Sorayomi/
          webRenderer: canvaskit
